# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog2(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox)
        self.label_153 = QtWidgets.QLabel(Dialog)
        self.label_153.setText("")
        self.label_153.setObjectName("label_153")
        self.horizontalLayout_8.addWidget(self.label_153)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_8.addWidget(self.lineEdit)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_8.addWidget(self.lineEdit_2)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_8.addWidget(self.line)
        self.label_154 = QtWidgets.QLabel(Dialog)
        self.label_154.setText("")
        self.label_154.setObjectName("label_154")
        self.horizontalLayout_8.addWidget(self.label_154)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_9.addWidget(self.lineEdit_3)
        self.label_155 = QtWidgets.QLabel(Dialog)
        self.label_155.setText("")
        self.label_155.setObjectName("label_155")
        self.horizontalLayout_9.addWidget(self.label_155)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_9.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_9.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_9.addWidget(self.lineEdit_6)
        self.label_157 = QtWidgets.QLabel(Dialog)
        self.label_157.setText("")
        self.label_157.setObjectName("label_157")
        self.horizontalLayout_9.addWidget(self.label_157)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_10.addWidget(self.label_3)
        self.lineEdit_7 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_10.addWidget(self.lineEdit_7)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_10.addWidget(self.lineEdit_8)
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_10.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_10.addWidget(self.pushButton_2)
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_10.addWidget(self.pushButton_4)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_10.addWidget(self.pushButton)
        self.label_156 = QtWidgets.QLabel(Dialog)
        self.label_156.setText("")
        self.label_156.setObjectName("label_156")
        self.horizontalLayout_10.addWidget(self.label_156)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_30 = QtWidgets.QLabel(Dialog)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 4, 2, 1, 1)
        self.label_62 = QtWidgets.QLabel(Dialog)
        self.label_62.setText("")
        self.label_62.setObjectName("label_62")
        self.gridLayout.addWidget(self.label_62, 4, 7, 1, 1)
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 6, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(Dialog)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 6, 2, 1, 1)
        self.label_46 = QtWidgets.QLabel(Dialog)
        self.label_46.setText("")
        self.label_46.setObjectName("label_46")
        self.gridLayout.addWidget(self.label_46, 2, 5, 1, 1)
        self.label_76 = QtWidgets.QLabel(Dialog)
        self.label_76.setText("")
        self.label_76.setObjectName("label_76")
        self.gridLayout.addWidget(self.label_76, 4, 9, 1, 1)
        self.label_64 = QtWidgets.QLabel(Dialog)
        self.label_64.setText("")
        self.label_64.setObjectName("label_64")
        self.gridLayout.addWidget(self.label_64, 5, 7, 1, 1)
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 3, 1, 1, 1)
        self.label_80 = QtWidgets.QLabel(Dialog)
        self.label_80.setText("")
        self.label_80.setObjectName("label_80")
        self.gridLayout.addWidget(self.label_80, 6, 9, 1, 1)
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 2, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(Dialog)
        self.label_59.setObjectName("label_59")
        self.gridLayout.addWidget(self.label_59, 3, 6, 1, 1)
        self.label_35 = QtWidgets.QLabel(Dialog)
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.gridLayout.addWidget(self.label_35, 2, 3, 1, 1)
        self.label_61 = QtWidgets.QLabel(Dialog)
        self.label_61.setObjectName("label_61")
        self.gridLayout.addWidget(self.label_61, 4, 6, 1, 1)
        self.label_58 = QtWidgets.QLabel(Dialog)
        self.label_58.setText("")
        self.label_58.setObjectName("label_58")
        self.gridLayout.addWidget(self.label_58, 2, 7, 1, 1)
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 5, 0, 1, 1)
        self.label_72 = QtWidgets.QLabel(Dialog)
        self.label_72.setText("")
        self.label_72.setObjectName("label_72")
        self.gridLayout.addWidget(self.label_72, 2, 9, 1, 1)
        self.label_74 = QtWidgets.QLabel(Dialog)
        self.label_74.setText("")
        self.label_74.setObjectName("label_74")
        self.gridLayout.addWidget(self.label_74, 3, 9, 1, 1)
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_51 = QtWidgets.QLabel(Dialog)
        self.label_51.setObjectName("label_51")
        self.gridLayout.addWidget(self.label_51, 5, 4, 1, 1)
        self.label_37 = QtWidgets.QLabel(Dialog)
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.gridLayout.addWidget(self.label_37, 4, 3, 1, 1)
        self.label_55 = QtWidgets.QLabel(Dialog)
        self.label_55.setText("")
        self.label_55.setObjectName("label_55")
        self.gridLayout.addWidget(self.label_55, 6, 5, 1, 1)
        self.label_54 = QtWidgets.QLabel(Dialog)
        self.label_54.setText("")
        self.label_54.setObjectName("label_54")
        self.gridLayout.addWidget(self.label_54, 5, 5, 1, 1)
        self.label_75 = QtWidgets.QLabel(Dialog)
        self.label_75.setObjectName("label_75")
        self.gridLayout.addWidget(self.label_75, 4, 8, 1, 1)
        self.label_28 = QtWidgets.QLabel(Dialog)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 2, 2, 1, 1)
        self.label_69 = QtWidgets.QLabel(Dialog)
        self.label_69.setObjectName("label_69")
        self.gridLayout.addWidget(self.label_69, 0, 8, 1, 1)
        self.label_79 = QtWidgets.QLabel(Dialog)
        self.label_79.setObjectName("label_79")
        self.gridLayout.addWidget(self.label_79, 6, 8, 1, 1)
        self.label_78 = QtWidgets.QLabel(Dialog)
        self.label_78.setText("")
        self.label_78.setObjectName("label_78")
        self.gridLayout.addWidget(self.label_78, 5, 9, 1, 1)
        self.label_66 = QtWidgets.QLabel(Dialog)
        self.label_66.setText("")
        self.label_66.setObjectName("label_66")
        self.gridLayout.addWidget(self.label_66, 6, 7, 1, 1)
        self.label_43 = QtWidgets.QLabel(Dialog)
        self.label_43.setObjectName("label_43")
        self.gridLayout.addWidget(self.label_43, 0, 6, 1, 1)
        self.label_57 = QtWidgets.QLabel(Dialog)
        self.label_57.setObjectName("label_57")
        self.gridLayout.addWidget(self.label_57, 2, 6, 1, 1)
        self.label_42 = QtWidgets.QLabel(Dialog)
        self.label_42.setText("")
        self.label_42.setObjectName("label_42")
        self.gridLayout.addWidget(self.label_42, 0, 5, 1, 1)
        self.label_45 = QtWidgets.QLabel(Dialog)
        self.label_45.setObjectName("label_45")
        self.gridLayout.addWidget(self.label_45, 2, 4, 1, 1)
        self.label_73 = QtWidgets.QLabel(Dialog)
        self.label_73.setObjectName("label_73")
        self.gridLayout.addWidget(self.label_73, 3, 8, 1, 1)
        self.label_63 = QtWidgets.QLabel(Dialog)
        self.label_63.setObjectName("label_63")
        self.gridLayout.addWidget(self.label_63, 5, 6, 1, 1)
        self.label_31 = QtWidgets.QLabel(Dialog)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 5, 2, 1, 1)
        self.label_50 = QtWidgets.QLabel(Dialog)
        self.label_50.setText("")
        self.label_50.setObjectName("label_50")
        self.gridLayout.addWidget(self.label_50, 4, 5, 1, 1)
        self.label_44 = QtWidgets.QLabel(Dialog)
        self.label_44.setText("")
        self.label_44.setObjectName("label_44")
        self.gridLayout.addWidget(self.label_44, 0, 7, 1, 1)
        self.label_65 = QtWidgets.QLabel(Dialog)
        self.label_65.setObjectName("label_65")
        self.gridLayout.addWidget(self.label_65, 6, 6, 1, 1)
        self.label_77 = QtWidgets.QLabel(Dialog)
        self.label_77.setObjectName("label_77")
        self.gridLayout.addWidget(self.label_77, 5, 8, 1, 1)
        self.label_29 = QtWidgets.QLabel(Dialog)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 3, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(Dialog)
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 0, 3, 1, 1)
        self.label_52 = QtWidgets.QLabel(Dialog)
        self.label_52.setObjectName("label_52")
        self.gridLayout.addWidget(self.label_52, 6, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 4, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(Dialog)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 0, 2, 1, 1)
        self.label_41 = QtWidgets.QLabel(Dialog)
        self.label_41.setObjectName("label_41")
        self.gridLayout.addWidget(self.label_41, 0, 4, 1, 1)
        self.label_36 = QtWidgets.QLabel(Dialog)
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.gridLayout.addWidget(self.label_36, 3, 3, 1, 1)
        self.label_47 = QtWidgets.QLabel(Dialog)
        self.label_47.setObjectName("label_47")
        self.gridLayout.addWidget(self.label_47, 3, 4, 1, 1)
        self.label_70 = QtWidgets.QLabel(Dialog)
        self.label_70.setObjectName("label_70")
        self.gridLayout.addWidget(self.label_70, 2, 8, 1, 1)
        self.label_48 = QtWidgets.QLabel(Dialog)
        self.label_48.setText("")
        self.label_48.setObjectName("label_48")
        self.gridLayout.addWidget(self.label_48, 3, 5, 1, 1)
        self.label_49 = QtWidgets.QLabel(Dialog)
        self.label_49.setObjectName("label_49")
        self.gridLayout.addWidget(self.label_49, 4, 4, 1, 1)
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 4, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 5, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(Dialog)
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.gridLayout.addWidget(self.label_39, 6, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_71 = QtWidgets.QLabel(Dialog)
        self.label_71.setText("")
        self.label_71.setObjectName("label_71")
        self.gridLayout.addWidget(self.label_71, 0, 9, 1, 1)
        self.label_60 = QtWidgets.QLabel(Dialog)
        self.label_60.setText("")
        self.label_60.setObjectName("label_60")
        self.gridLayout.addWidget(self.label_60, 3, 7, 1, 1)
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 6, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(Dialog)
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.gridLayout.addWidget(self.label_38, 5, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 4, 1, 1)
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 1, 5, 1, 1)
        self.label_26 = QtWidgets.QLabel(Dialog)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 1, 6, 1, 1)
        self.label_33 = QtWidgets.QLabel(Dialog)
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 1, 7, 1, 1)
        self.label_40 = QtWidgets.QLabel(Dialog)
        self.label_40.setObjectName("label_40")
        self.gridLayout.addWidget(self.label_40, 1, 8, 1, 1)
        self.label_53 = QtWidgets.QLabel(Dialog)
        self.label_53.setText("")
        self.label_53.setObjectName("label_53")
        self.gridLayout.addWidget(self.label_53, 1, 9, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "管理员界面"))
        self.label.setText(_translate("Dialog", "温控模式："))
        self.comboBox.setItemText(0, _translate("Dialog", "ColdOnly"))
        self.comboBox.setItemText(1, _translate("Dialog", "WarmOnly"))
        self.comboBox.setItemText(2, _translate("Dialog", "ColdWarm"))
        self.label_4.setText(_translate("Dialog", "温控范围："))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "最低温"))
        self.label_6.setText(_translate("Dialog", "——"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "最高温"))
        self.label_2.setText(_translate("Dialog", "缺省温度："))
        self.lineEdit_3.setPlaceholderText(_translate("Dialog", "默认室温"))
        self.label_5.setText(_translate("Dialog", "费率："))
        self.lineEdit_4.setPlaceholderText(_translate("Dialog", "高风"))
        self.lineEdit_5.setPlaceholderText(_translate("Dialog", "中风"))
        self.lineEdit_6.setPlaceholderText(_translate("Dialog", "低风"))
        self.label_3.setText(_translate("Dialog", "服务对象："))
        self.label_7.setText(_translate("Dialog", "等待时间"))
        self.pushButton_3.setText(_translate("Dialog", "开机"))
        self.pushButton_2.setText(_translate("Dialog", "应用"))
        self.pushButton_4.setText(_translate("Dialog", "监控"))
        self.pushButton.setText(_translate("Dialog", "结束监控"))
        self.label_30.setText(_translate("Dialog", "空调模式："))
        self.label_18.setText(_translate("Dialog", "风速："))
        self.label_32.setText(_translate("Dialog", "风速："))
        self.label_15.setText(_translate("Dialog", "室温："))
        self.label_59.setText(_translate("Dialog", "室温："))
        self.label_61.setText(_translate("Dialog", "空调模式："))
        self.label_17.setText(_translate("Dialog", "设定温度："))
        self.label_13.setText(_translate("Dialog", "房间号："))
        self.label_51.setText(_translate("Dialog", "设定温度："))
        self.label_75.setText(_translate("Dialog", "空调模式："))
        self.label_28.setText(_translate("Dialog", "空调状态："))
        self.label_69.setText(_translate("Dialog", "房间号："))
        self.label_79.setText(_translate("Dialog", "风速："))
        self.label_43.setText(_translate("Dialog", "房间号："))
        self.label_57.setText(_translate("Dialog", "空调状态："))
        self.label_45.setText(_translate("Dialog", "空调状态："))
        self.label_73.setText(_translate("Dialog", "室温："))
        self.label_63.setText(_translate("Dialog", "设定温度："))
        self.label_31.setText(_translate("Dialog", "设定温度："))
        self.label_65.setText(_translate("Dialog", "风速："))
        self.label_77.setText(_translate("Dialog", "设定温度："))
        self.label_29.setText(_translate("Dialog", "室温："))
        self.label_52.setText(_translate("Dialog", "风速："))
        self.label_16.setText(_translate("Dialog", "空调模式："))
        self.label_27.setText(_translate("Dialog", "房间号："))
        self.label_41.setText(_translate("Dialog", "房间号："))
        self.label_47.setText(_translate("Dialog", "室温："))
        self.label_70.setText(_translate("Dialog", "空调状态："))
        self.label_49.setText(_translate("Dialog", "空调模式："))
        self.label_14.setText(_translate("Dialog", "空调状态："))
        self.label_8.setText(_translate("Dialog", "入住状况："))
        self.label_10.setText(_translate("Dialog", "入住状况："))
        self.label_12.setText(_translate("Dialog", "入住状况："))
        self.label_26.setText(_translate("Dialog", "入住状况："))
        self.label_40.setText(_translate("Dialog", "入住状况："))

    def addmessage(self, feedback):
        self.label_20.setText(feedback[0])
        self.label_9.setText(feedback[1])
        self.label_21.setText(feedback[2])
        self.label_22.setText(feedback[3])
        self.label_23.setText(feedback[4])
        self.label_24.setText(feedback[5])
        self.label_25.setText(feedback[6])

        self.label_34.setText(feedback[7])
        self.label_11.setText(feedback[8])
        self.label_35.setText(feedback[9])
        self.label_36.setText(feedback[10])
        self.label_37.setText(feedback[11])
        self.label_38.setText(feedback[12])
        self.label_39.setText(feedback[13])

        self.label_42.setText(feedback[14])
        self.label_19.setText(feedback[15])
        self.label_46.setText(feedback[16])
        self.label_48.setText(feedback[17])
        self.label_50.setText(feedback[18])
        self.label_54.setText(feedback[19])
        self.label_55.setText(feedback[20])

        self.label_44.setText(feedback[21])
        self.label_33.setText(feedback[22])
        self.label_58.setText(feedback[23])
        self.label_60.setText(feedback[24])
        self.label_62.setText(feedback[25])
        self.label_64.setText(feedback[26])
        self.label_66.setText(feedback[27])

        self.label_71.setText(feedback[28])
        self.label_53.setText(feedback[29])
        self.label_72.setText(feedback[30])
        self.label_74.setText(feedback[31])
        self.label_76.setText(feedback[32])
        self.label_78.setText(feedback[33])
        self.label_80.setText(feedback[34])

    def stop_supervise(self):
        self.label_20.clear()
        self.label_9.clear()
        self.label_21.clear()
        self.label_22.clear()
        self.label_23.clear()
        self.label_24.clear()
        self.label_25.clear()

        self.label_34.clear()
        self.label_11.clear()
        self.label_35.clear()
        self.label_36.clear()
        self.label_37.clear()
        self.label_38.clear()
        self.label_39.clear()

        self.label_42.clear()
        self.label_19.clear()
        self.label_46.clear()
        self.label_48.clear()
        self.label_50.clear()
        self.label_54.clear()
        self.label_55.clear()

        self.label_44.clear()
        self.label_33.clear()
        self.label_58.clear()
        self.label_60.clear()
        self.label_62.clear()
        self.label_64.clear()
        self.label_66.clear()

        self.label_71.clear()
        self.label_53.clear()
        self.label_72.clear()
        self.label_74.clear()
        self.label_76.clear()
        self.label_78.clear()
        self.label_80.clear()